MvcApiExamenAzureAMH/Models/ErrorViewModel.cs
using System;

namespace MvcApiExamenAzureAMH.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcApiExamenAzureAMH/Models/Personaje.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApiExamenAzureAMH.Models
{
    public class Personaje
    {
        public int IdPersonaje { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public int IdSerie { get; set; }
    }
}

MvcApiExamenAzureAMH/Models/Serie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApiExamenAzureAMH.Models
{
    public class Serie
    {
        public int IdSerie { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public double Puntuacion { get; set; }
        public int Año { get; set; }
    }
}

MvcApiExamenAzureAMH/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcApiExamenAzureAMH.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApiExamenAzureAMH.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcApiExamenAzureAMH/Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiExamenAzureAMH.Models;
using MvcApiExamenAzureAMH.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApiExamenAzureAMH.Controllers
{
    public class PersonajesController : Controller
    {
        private ServiceApiSeries service;

        public PersonajesController(ServiceApiSeries service)
        {
            this.service = service;
        }

        public IActionResult PersonajesCliente()
        {
            return View();
        }

        public async Task<IActionResult> PersonajesServidor()
        {
            List<Personaje> pjs = await this.service.GetPersonajesAsync();
            return View(pjs);
        }

        public IActionResult CreatePersonaje()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreatePersonaje(string nombre,string imagen,int idserie)
        {
            await this.service.InsertPersonajeAsync(nombre,imagen,idserie);
            return RedirectToAction("PersonajesServidor");
        }

        public async Task<IActionResult> DeletePersonaje(int idpj)
        {
            await this.service.DeletePersonajeAsync(idpj);
            return RedirectToAction("PersonajesServidor");
        }

        public async Task<IActionResult> UpdatePersonajeSerie()
        {
            List<Personaje> pjs = await this.service.GetPersonajesAsync();
            List<Serie> series = await this.service.GetSeriesAsync();
            ViewData["SERIES"] = series;
            return View(pjs);
        }

        [HttpPost]
        public async Task<ActionResult> UpdatePersonajeSerie(int idpersonaje,int idserie)
        {
            await this.service.UpdatePersonajeSerieAsync(idpersonaje, idserie);
            return RedirectToAction("PersonajesServidor");
        }
    }
}

MvcApiExamenAzureAMH/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcApiExamenAzureAMH.Models;
using MvcApiExamenAzureAMH.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApiExamenAzureAMH.Controllers
{
    public class SeriesController : Controller
    {
        private ServiceApiSeries service;

        public SeriesController(ServiceApiSeries service)
        {
            this.service = service;
        }

        public IActionResult SeriesCliente()
        {
            return View();
        }

        public async Task<IActionResult> SeriesServidor()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            return View(series);           
        }

        public async Task<IActionResult> DetallesSerie(int idserie)
        {
            Serie serie = await this.service.FindSerieAsync(idserie);
            return View(serie);
        }

        public async Task <IActionResult> PersonajesSerie(int idserie)
        {
            List <Personaje> personajes= await this.service.FindPersonajesSerieAsync(idserie);
            return View(personajes);
        }

        public async Task <IActionResult> UpdateSerie(int idserie)
        {
            Serie serie = await this.service.FindSerieAsync(idserie);
            return View(serie);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSerie(Serie serie)
        {
            await this.service.UpdateSerieAsync(serie.IdSerie, serie.Nombre, serie.Imagen,serie.Puntuacion,serie.Año);
            return RedirectToAction("SeriesServidor");
        }


    }
}

MvcApiExamenAzureAMH/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcApiExamenAzureAMH/Views/Personajes/CreatePersonaje.cshtml
@model MvcApiExamenAzureAMH.Models.Personaje

@{
    ViewData["Title"] = "CreatePersonaje";
}

<h1>CreatePersonaje</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePersonaje">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
              
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdSerie" class="control-label"></label>
                <input asp-for="IdSerie" class="form-control" />
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PersonajesServidor">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiExamenAzureAMH/Views/Personajes/PersonajesCliente.cshtml
<h1>Personajes Cliente</h1>

@section Scripts{
    <script>
        var urlApi = "https://apiexamenamh.azurewebsites.net/";
        $(document).ready(function () {
            $("#botonmostrar").click(function () {
                var id = $("#cajanumero").val();
                var request = "/api/Series/PersonajesSerie/" + id;
                $.ajax({
                    url: urlApi + request,
                    method: "GET",
                    dataType: "json",
                    success: function (data) {
                        var html = "";
                        $.each(data, function (index, pj) {
                            html += "<tr>"
                            html += "<td>" + pj.idPersonaje + "</td>";
                            html += "<td>" + pj.nombre + "</td>";
                            html += "<td><img src='" + pj.imagen + "' style='width:150px;height:150px'/></td>";
                            html += "<td>" + pj.idSerie + "</td>";
                            html += "</tr>"
                        });
                        $("#tablaPersonajes tbody").html(html);
                    }
                })


            });

        });

    </script>
}
<label>Inserte la id de la serie: </label>
<input type="text" id="cajanumero" class="form-control" />
<br />
<button id="botonmostrar" class="btn btn-success">Mostrar</button>
<br />
<table class="table table-dark" id="tablaPersonajes">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Id Serie</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

MvcApiExamenAzureAMH/Views/Personajes/PersonajesServidor.cshtml
@model IEnumerable<MvcApiExamenAzureAMH.Models.Personaje>

@{
    ViewData["Title"] = "SeriesServidor";
}

<h1>Personajes Servidor</h1>

<p>
    <a asp-action="UpdatePersonajeSerie">Mover Personajes</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" style="width:150px;height:150px"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
            <td>
              <a class="btn btn-danger" asp-action="DeletePersonaje" asp-controller="Personajes" asp-route-idpj="@item.IdPersonaje">Eliminar</a>
            </td>
        </tr>
}
        <td colspan="5" class="text-center">
            <a class="btn btn-success" asp-action="CreatePersonaje" asp-controller="Personajes">Nuevo</a>
        </td>
    </tbody>
</table>

MvcApiExamenAzureAMH/Views/Personajes/UpdatePersonajeSerie.cshtml
@model List<Personaje> 

@{ 
    List<Serie> series = ViewData["SERIES"] as List<Serie>;
}

<form method="post">
    <select name="idpersonaje" class="form-control">
        @foreach (Personaje pj in Model)
        {
            <option value="@pj.IdPersonaje" >@pj.Nombre</option>
        }
    </select>
    <br />
    <br />
    <select name="idserie" class="form-control">
        @foreach (Serie ser in series)
        {
            <option value="@ser.IdSerie">@ser.Nombre</option>
        }
    </select>

    <button type="submit" class="btn btn-success">Mover personaje</button>
</form>

MvcApiExamenAzureAMH/Views/Series/DetallesSerie.cshtml
@model MvcApiExamenAzureAMH.Models.Serie

@{
    ViewData["Title"] = "DetallesSerie";
}

<h1>Detalles Serie</h1>

<div>
    <h4>Serie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Puntuacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Puntuacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Año)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Año)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="SeriesServidor">Back to List</a>
</div>

MvcApiExamenAzureAMH/Views/Series/PersonajesSerie.cshtml
@model IEnumerable<MvcApiExamenAzureAMH.Models.Personaje>

@{
    ViewData["Title"] = "PersonajesSerie";
}

<h1>PersonajesSerie</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPersonaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" style="width:150px;height:150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
        </tr>
}
    </tbody>
</table>

MvcApiExamenAzureAMH/Views/Series/SeriesCliente.cshtml
<h1>Series cliente</h1>

@section Scripts{
    <script>
        var urlApi = "https://apiexamenamh.azurewebsites.net/";
        $(document).ready(function () {
            cargarSeries();

            $("#botoninsert").click(function () {
                var nombre = $("#cajanombre").val();
                var imagen = $("#cajaimagen").val();
                var puntuacion = $("#cajapuntuacion").val();
                var año = $("#cajaaño").val();
                var serie = new Object();
                serie.idSerie = 0;
                serie.nombre = nombre;
                serie.imagen = imagen;
                serie.puntuacion = puntuacion;
                serie.año = año;
                var json = JSON.stringify(serie);
                var request = "/api/Series";
                $.ajax({
                    url: urlApi + request,
                    type: "POST",
                    data: json,
                    contentType: "application/json",
                    success: function () {
                        cargarSeries();
                    }
                });
            });

            $("#botondelete").click(function () {
                var id = $("#cajanumero").val();
                var request = "/api/series/" + id;
                $.ajax({
                    url: urlApi + request,
                    type: "DELETE",
                    success: function () {
                        cargarSeries();
                    }
                });
            });

        });

        function cargarSeries() {
            var request = "/api/Series";
            $.ajax({
                url: urlApi + request,
                method: "GET",
                dataType: "json",
                success: function (data) {
                    var html = "";
                    $.each(data, function (index, serie) {
                        html += "<tr>"
                        html += "<td>" + serie.idSerie + "</td>";
                        html += "<td>" + serie.nombre + "</td>";
                        html += "<td><img src='" + serie.imagen + "' style='width:150px;height:150px'/></td>";
                        html += "<td>" + serie.puntuacion + "</td>";
                        html += "<td>" + serie.año + "</td>";
                        html += "</tr>"
                    });
                    $("#tablaSeries tbody").html(html);
                }
            })
        }
    </script>
}

<label>Nombre:</label>
<input type="text" id="cajanombre" class="form-control" />
<br />

<label>Imagen:</label>
<input type="text" id="cajaimagen" class="form-control" />
<br />

<label>Puntuacion:</label>
<input type="text" id="cajapuntuacion" class="form-control" />
<br />

<label>Año:</label>
<input type="text" id="cajaaño" class="form-control" />
<br />

<button id="botoninsert" class="btn btn-success">Insert</button>
<br />

<label>Inserte el id de la serie a eliminar:</label>
<input type="text" id="cajanumero" class="form-control" />
<br />

<button id="botondelete" class="btn btn-danger">Delete</button>
<br />

<table class="table table-warning" id="tablaSeries">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Puntuacion</th>
            <th>Año</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

MvcApiExamenAzureAMH/Views/Series/SeriesServidor.cshtml
@model IEnumerable<MvcApiExamenAzureAMH.Models.Serie>

@{
    ViewData["Title"] = "SeriesServidor";
}

<h1>Series Servidor</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puntuacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Año)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" style="width:150px;height:150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Puntuacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Año)
            </td>
            <td>
               <a asp-controller="Series" asp-action="DetallesSerie" asp-route-idserie="@item.IdSerie" class="btn btn-info">Detalles</a>
               <a asp-controller="Series" asp-action="UpdateSerie" asp-route-idserie="@item.IdSerie" class="btn btn-warning">Update</a>
               <a asp-controller="Series" asp-action="PersonajesSerie" asp-route-idserie="@item.IdSerie" class="btn btn-success">Personajes</a>
            
            </td>
        </tr>
}
    </tbody>
</table>

MvcApiExamenAzureAMH/Views/Series/UpdateSerie.cshtml
@model MvcApiExamenAzureAMH.Models.Serie

@{
    ViewData["Title"] = "UpdateSerie";
}

<h1>Update Serie</h1>

<h4>Serie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateSerie">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input hidden asp-for="IdSerie" class="form-control" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puntuacion" class="control-label"></label>
                <input asp-for="Puntuacion" class="form-control" />
                <span asp-validation-for="Puntuacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Año" class="control-label"></label>
                <input asp-for="Año" class="form-control" />
                <span asp-validation-for="Año" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SeriesServidor">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcApiExamenAzureAMH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApiExamenAzureAMH</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApiExamenAzureAMH</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="SeriesCliente">Series (Cliente)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="PersonajesCliente">Personajes (Cliente)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="SeriesServidor">Series (Servidor)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personajes" asp-action="PersonajesServidor">Personajes (Servidor)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcApiExamenAzureAMH - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>